A notebook to visualize and understand the cleaned data, which will be used to train an ML model for the Romberg test.

## 1. Clone Repo

In [1]:
!git clone https://github.com/A2AppRom/sophia-romberg-data

Cloning into 'sophia-romberg-data'...
remote: Enumerating objects: 100, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 100 (delta 23), reused 68 (delta 14), pack-reused 0 (from 0)
Receiving objects: 100% (100/100), 3.74 MiB | 11.89 MiB/s, done.
Resolving deltas: 100% (23/23), done.

## 2. Pandas
This library is used to create Dataframes, which are Python object representations of CSV files. Pandas is really useful for doing preparing data in a format that can be directly used to train a machine learning model.

Here we are just using Pandas to visualize the data. Check out `notebooks/data-preprocessing.ipynb` for the full script used to create this dataset.

In [3]:
import pandas as pd

## 3. Visualize Raw Data
Look at a sample of the raw accelerometer data collected from the Sensor logger app. These files were organized by subject and session as follows:

/ data

      / 0_STABLE
          / session_0
              eyes_open.csv
              eyes_closed.csv
              Metadata.csv
          / session_1
              eyes_open.csv
              eyes_closed.csv
              Metadata.csv
          ...
          / session_n
      
      / 1_IMPAIRED
          / session_0
              eyes_open.csv
              eyes_closed.csv
              Metadata.csv
      ...
      / n_[STABLE/IMPAIRED]

In [4]:
# look at first five columns of eyes_open.csv for a single session
open = pd.read_csv('/content/sophia-romberg-data/data_unlabeled/subject_0/session_0/eyes_open.csv')
open.head()

                  time  seconds_elapsed         z         y         x
0  1773251275697468000         0.078468 -0.706734  0.766391  0.830043
1  1773251275707503900         0.088504 -0.276636  1.245918  0.588294
2  1773251275717539800         0.098540 -0.272278  1.365787  0.088636
3  1773251275727575800         0.108576 -0.231632  1.255628 -0.409468
4  1773251275737611800         0.118612  0.015314  0.872627 -0.453476

In [11]:
open.shape
# tuple representing (rows, columns)

(4541, 5)

In [8]:
# look at first five columns of eyes_closed.csv for a single session
closed = pd.read_csv('/content/sophia-romberg-data/data_unlabeled/subject_0/session_0/eyes_closed.csv')
closed.head()

                  time  seconds_elapsed         z         y         x
0  1773251345600715500         0.075716 -0.416073  0.224907 -0.184109
1  1773251345610751700         0.085752 -0.601396  0.261564 -0.716480
2  1773251345620787700         0.095788 -0.965136  0.324552 -1.342677
3  1773251345630824400         0.105824 -1.177589  0.397456 -1.789139
4  1773251345640860700         0.115861 -1.160733  0.427730 -1.856959

In [9]:
closed.shape

(4517, 5)

In [10]:
closed.columns

Index(['time', 'seconds_elapsed', 'z', 'y', 'x'], dtype='object')

## 4. Visualize Cleaned Data

In [18]:
data = pd.read_csv('/content/sophia-romberg-data/labeled_data_with_features.csv')

In [19]:
data = data.drop(columns=['Unnamed: 0']) # this column was added when exporting the CSV from colab, so it needs to be removed using .drop()
data

,subject_id,session_id,label,eyes_open_duration,eyes_closed_duration,rms_open,rms_closed,std_mag_open,std_mag_closed,romberg_ratio_rms,romberg_ratio_std
0,subject_3,session_0,stable,42798669300,42738772700,0.383673,0.399179,0.350194,0.360620,1.040417,1.029774
1,subject_5,session_0,stable,44073496300,46836302100,0.731343,1.232582,0.699133,1.186408,1.685369,1.696969
2,subject_5,session_1,stable,46752404600,46174638600,1.376920,1.469639,1.318487,1.411359,1.067338,1.070439
3,subject_2,session_0,stable,42846806800,43068919300,0.366372,0.411984,0.328285,0.376108,1.124497,1.145674
4,subject_1,session_0,stable,58753421600,58753421600,0.584403,0.584403,0.556785,0.556785,1.000000,1.000000
5,subject_0,session_0,stable,45564259500,45324047600,0.400963,0.593192,0.342887,0.555259,1.479420,1.619363
6,subject_7,session_0,stable,43841331400,43120434200,1.012034,0.638751,0.977059,0.600707,0.631156,0.614811
7,subject_6,session_0,stable,43415210500,42871728700,1.130583,0.861383,1.071346,0.772657,0.761893,0.721202
8,subject_6,session_1,stable,43759096100,42909666000,0.894356,0.627078,0.834923,0.557199,0.701151,0.667366
9,subject_4,session_0,stable,32043969000,34405365500,0.736683,0.376203,0.621835,0.308457,0.510672,0.496044

In [20]:
data.shape

(10, 11)